# Generated by Django 5.1.3 on 2025-11-30 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherinfo',
            name='avatar',
        ),
    ]
