# Generated by Django 5.2.8 on 2025-11-29 18:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OperationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("login", "登录"),
                            ("logout", "登出"),
                            ("create", "创建"),
                            ("update", "更新"),
                            ("delete", "删除"),
                            ("approve", "审核通过"),
                            ("reject", "审核拒绝"),
                        ],
                        max_length=20,
                        verbose_name="操作类型",
                    ),
                ),
                (
                    "object_type",
                    models.CharField(max_length=100, verbose_name="操作对象类型"),
                ),
                (
                    "object_id",
                    models.CharField(max_length=100, verbose_name="操作对象ID"),
                ),
                (
                    "object_name",
                    models.CharField(max_length=200, verbose_name="操作对象名称"),
                ),
                ("ip_address", models.CharField(max_length=50, verbose_name="IP地址")),
                ("description", models.TextField(verbose_name="操作描述")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="操作时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="操作用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "操作日志",
                "verbose_name_plural": "操作日志管理",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="订单编号"
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="订单名称")),
                ("student_count", models.IntegerField(verbose_name="服务学生数")),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("one_to_one", "一对一"),
                            ("one_to_two", "一对二"),
                            ("custom", "自定义"),
                        ],
                        max_length=20,
                        verbose_name="服务类型",
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="单价"
                    ),
                ),
                (
                    "total_hours",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="总时长"
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="总金额"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待开课"),
                            ("ongoing", "进行中"),
                            ("completed", "已完成"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="订单状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_orders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="分配教师",
                    ),
                ),
            ],
            options={
                "verbose_name": "订单",
                "verbose_name_plural": "订单管理",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SalaryApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "apply_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="申请金额"
                    ),
                ),
                (
                    "proof_file",
                    models.FileField(upload_to="proofs/", verbose_name="证明材料"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待审核"),
                            ("approved", "通过"),
                            ("rejected", "拒绝"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="审核状态",
                    ),
                ),
                (
                    "review_note",
                    models.TextField(blank=True, null=True, verbose_name="审核备注"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="申请时间"),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="审核时间"
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="salary_applications",
                        to="orders.order",
                        verbose_name="关联订单",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_applications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="审核人",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="salary_applications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="申请教师",
                    ),
                ),
            ],
            options={
                "verbose_name": "工资申请",
                "verbose_name_plural": "工资申请管理",
                "ordering": ["-created_at"],
            },
        ),
    ]
