# Generated by Django 5.1.3 on 2025-11-30 05:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salaryapplication',
            name='review_note',
        ),
        migrations.RemoveField(
            model_name='salaryapplication',
            name='reviewed_at',
        ),
        migrations.RemoveField(
            model_name='salaryapplication',
            name='reviewed_by',
        ),
        migrations.AddField(
            model_name='salaryapplication',
            name='application_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='申请编号'),
        ),
        migrations.AddField(
            model_name='salaryapplication',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='审批时间'),
        ),
        migrations.AddField(
            model_name='salaryapplication',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_applications', to=settings.AUTH_USER_MODEL, verbose_name='审批人'),
        ),
        migrations.AddField(
            model_name='salaryapplication',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='拒绝时间'),
        ),
        migrations.AddField(
            model_name='salaryapplication',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True, verbose_name='拒绝原因'),
        ),
        migrations.AddField(
            model_name='salaryapplication',
            name='remarks',
            field=models.TextField(blank=True, null=True, verbose_name='备注'),
        ),
        migrations.AddField(
            model_name='salaryapplication',
            name='withdrawn_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='撤回时间'),
        ),
        migrations.AlterField(
            model_name='salaryapplication',
            name='status',
            field=models.CharField(choices=[('pending', '待审核'), ('approved', '通过'), ('rejected', '拒绝'), ('withdrawn', '已撤回')], default='pending', max_length=20, verbose_name='审核状态'),
        ),
    ]
